version: '2'
services:
    testpostgresql-app:
        image: testpostgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testpostgresql-postgresql:5432/TestPostgreSQL
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=testpostgresql-elasticsearch:9300
        ports:
            - 8080:8080
    testpostgresql-postgresql:
        extends:
            file: postgresql.yml
            service: testpostgresql-postgresql
    testpostgresql-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: testpostgresql-elasticsearch
